vhost:
  image: viljaste/vhost:latest
  hostname: vhost
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - vhostdata
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /:/host:ro
  environment:
    - SERVER_NAME=localhost
vhostdata:
  image: viljaste/data:latest
  hostname: vhostdata
  volumes:
    - /vhost
