vhost:
  image: dockerizedrupal/vhost:1.1.0
  hostname: vhost
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - vhost-data
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/hosts:/hosts
  environment:
    - SERVER_NAME=localhost
    - SERVER_ALIAS_1=localhost
    - TIMEZONE=Etc/UTC
    - PROXY_READ_TIMEOUT=900
    - PROTOCOLS=https,http
    - HOSTS_IP_ADDRESS=127.0.0.1
    - HTTP_BASIC_AUTH=Off
    - HTTP_BASIC_AUTH_USERNAME=container
    - HTTP_BASIC_AUTH_PASSWORD=
    - HTTP_BASIC_AUTH_RANDOM=Off
    - HTTP_BASIC_AUTH_RANDOM_PASSWORD_LENGTH=32
    - HTTP_BASIC_AUTH_RANDOM_PASSWORD_SALT=
vhost-data:
  image: dockerizedrupal/data:1.1.0
  hostname: vhost-data
  volumes:
    - /vhost
