vhost:
  image: dockerizedrupal/vhost:1.0.4
  hostname: vhost
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - vhost-data
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=900
    - PROTOCOLS=https,http
vhost-data:
  image: dockerizedrupal/data:1.0.3
  hostname: vhost-data
  volumes:
    - /vhost
