vhost:
  image: dockerizedrupal/vhost:1.0.2
  hostname: vhost
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - vhostdata
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=900
    - PROTOCOLS=https
vhostdata:
  image: dockerizedrupal/data:1.0.2
  hostname: vhostdata
  volumes:
    - /vhost
